databases:
  - name: shailes
    databaseName: shailes
    user: shailes

services:
  - type: web
    name: shailes
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shailes
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
