databases:
  - name: shailes_production
    databaseName: shailes_production
    user: shailes

services:
  - type: web
    name: shailes
    runtime: ruby
    buildCommand: "./bin/renderbuild.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shailes_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
